Folder PATH listing
Volume serial number is FC6B-FA6F
C:\USERS\TIJANI\DESKTOP\SMARTCLASSFACE\FACE_VERIFICATION_BASED_ATTENDANCE_SYSTEM-MASTER\FACE_VERIFICATION_BASED_ATTENDANCE_SYSTEM-MASTER\STRUCTURE.TXT
Invalid path - \USERS\TIJANI\DESKTOP\SMARTCLASSFACE\FACE_VERIFICATION_BASED_ATTENDANCE_SYSTEM-MASTER\FACE_VERIFICATION_BASED_ATTENDANCE_SYSTEM-MASTER\STRUCTURE.TXT
No subfolders exist 

